# Form implementation generated from reading ui file 'assets/GUI/untitled.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UNOlingo(object):
    def setupUi(self, UNOlingo):
        UNOlingo.setObjectName("UNOlingo")
        UNOlingo.resize(1280, 720)
        UNOlingo.setMinimumSize(QtCore.QSize(1280, 0))
        UNOlingo.setMaximumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/GUI\\../images/unolingo_P64_icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        UNOlingo.setWindowIcon(icon)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=UNOlingo)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-10, 0, 1301, 771))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Base_Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Base_Layout.setContentsMargins(0, 0, 0, 0)
        self.Base_Layout.setSpacing(9)
        self.Base_Layout.setObjectName("Base_Layout")
        self.pages = QtWidgets.QStackedWidget(parent=self.verticalLayoutWidget)
        self.pages.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pages.setAutoFillBackground(False)
        self.pages.setObjectName("pages")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.MistakesLabel = QtWidgets.QLabel(parent=self.page_3)
        self.MistakesLabel.setGeometry(QtCore.QRect(110, 200, 271, 121))
        self.MistakesLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MistakesLabel.setObjectName("MistakesLabel")
        self.Grade3 = QtWidgets.QLabel(parent=self.page_3)
        self.Grade3.setGeometry(QtCore.QRect(1030, 230, 51, 71))
        self.Grade3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Grade3.setObjectName("Grade3")
        self.Grade4 = QtWidgets.QLabel(parent=self.page_3)
        self.Grade4.setGeometry(QtCore.QRect(1100, 230, 51, 71))
        self.Grade4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Grade4.setObjectName("Grade4")
        self.GradesLabel = QtWidgets.QLabel(parent=self.page_3)
        self.GradesLabel.setGeometry(QtCore.QRect(430, 200, 512, 123))
        self.GradesLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.GradesLabel.setObjectName("GradesLabel")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.page_3)
        self.scrollArea.setGeometry(QtCore.QRect(130, 310, 1061, 271))
        self.scrollArea.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidget = QtWidgets.QWidget()
        self.scrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 1059, 269))
        self.scrollAreaWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.scrollAreaWidget.setObjectName("scrollAreaWidget")
        self.scrollGrid = QtWidgets.QGridLayout(self.scrollAreaWidget)
        self.scrollGrid.setObjectName("scrollGrid")
        self.scrollArea.setWidget(self.scrollAreaWidget)
        self.ResultsLabel = QtWidgets.QLabel(parent=self.page_3)
        self.ResultsLabel.setGeometry(QtCore.QRect(580, 20, 211, 151))
        self.ResultsLabel.setStyleSheet("font-size: 24px; color: #810031;")
        self.ResultsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ResultsLabel.setObjectName("ResultsLabel")
        self.Grade1 = QtWidgets.QLabel(parent=self.page_3)
        self.Grade1.setGeometry(QtCore.QRect(890, 230, 51, 71))
        self.Grade1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Grade1.setObjectName("Grade1")
        self.Grade5 = QtWidgets.QLabel(parent=self.page_3)
        self.Grade5.setGeometry(QtCore.QRect(1170, 230, 51, 71))
        self.Grade5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Grade5.setObjectName("Grade5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.page_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 600, 1151, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.ButtonsLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.ButtonsLayout.setContentsMargins(0, 0, 0, 0)
        self.ButtonsLayout.setObjectName("ButtonsLayout")
        self.SaveAndExit = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.SaveAndExit.setMinimumSize(QtCore.QSize(500, 70))
        self.SaveAndExit.setMaximumSize(QtCore.QSize(500, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setKerning(False)
        self.SaveAndExit.setFont(font)
        self.SaveAndExit.setStyleSheet("QPushButton {\n"
"    color: #eee;\n"
"    border: none;\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #7612b8\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #954af7\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #5b29f2\n"
"        );\n"
"    }")
        self.SaveAndExit.setObjectName("SaveAndExit")
        self.ButtonsLayout.addWidget(self.SaveAndExit)
        self.Repeat = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.Repeat.setMinimumSize(QtCore.QSize(500, 70))
        self.Repeat.setMaximumSize(QtCore.QSize(500, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setKerning(False)
        self.Repeat.setFont(font)
        self.Repeat.setStyleSheet("QPushButton {\n"
"    color: #eee;\n"
"    border: none;\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #7612b8\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #954af7\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #5b29f2\n"
"        );\n"
"    }")
        self.Repeat.setObjectName("Repeat")
        self.ButtonsLayout.addWidget(self.Repeat)
        self.AnswersLabel = QtWidgets.QLabel(parent=self.page_3)
        self.AnswersLabel.setGeometry(QtCore.QRect(440, 120, 512, 122))
        self.AnswersLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.AnswersLabel.setObjectName("AnswersLabel")
        self.Grade2 = QtWidgets.QLabel(parent=self.page_3)
        self.Grade2.setGeometry(QtCore.QRect(960, 230, 51, 71))
        self.Grade2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Grade2.setObjectName("Grade2")
        self.pages.addWidget(self.page_3)
        self.Lesson_screen = QtWidgets.QWidget()
        self.Lesson_screen.setObjectName("Lesson_screen")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.Lesson_screen)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1282, 591))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Main_Study_Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Main_Study_Layout.setContentsMargins(0, 0, 0, 0)
        self.Main_Study_Layout.setSpacing(0)
        self.Main_Study_Layout.setObjectName("Main_Study_Layout")
        spacerItem = QtWidgets.QSpacerItem(20, 170, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.Main_Study_Layout.addItem(spacerItem)
        self.Center_widget = QtWidgets.QWidget(parent=self.verticalLayoutWidget_2)
        self.Center_widget.setMinimumSize(QtCore.QSize(0, 160))
        self.Center_widget.setMaximumSize(QtCore.QSize(16777215, 160))
        self.Center_widget.setObjectName("Center_widget")
        self.The_word = QtWidgets.QLabel(parent=self.Center_widget)
        self.The_word.setGeometry(QtCore.QRect(10, 10, 1281, 110))
        self.The_word.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.The_word.setFont(font)
        self.The_word.setStyleSheet("")
        self.The_word.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.The_word.setObjectName("The_word")
        self.repeat_audio = QtWidgets.QPushButton(parent=self.Center_widget)
        self.repeat_audio.setGeometry(QtCore.QRect(250, 10, 100, 100))
        self.repeat_audio.setMinimumSize(QtCore.QSize(100, 100))
        self.repeat_audio.setMaximumSize(QtCore.QSize(100, 100))
        self.repeat_audio.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: none;\n"
"    border-radius: 50px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ccc\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #aaa\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }")
        self.repeat_audio.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/GUI\\../images/audio.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.repeat_audio.setIcon(icon1)
        self.repeat_audio.setIconSize(QtCore.QSize(60, 60))
        self.repeat_audio.setObjectName("repeat_audio")
        self.restart_lesson = QtWidgets.QPushButton(parent=self.Center_widget)
        self.restart_lesson.setEnabled(True)
        self.restart_lesson.setGeometry(QtCore.QRect(930, 10, 100, 100))
        self.restart_lesson.setMinimumSize(QtCore.QSize(100, 100))
        self.restart_lesson.setMaximumSize(QtCore.QSize(100, 100))
        self.restart_lesson.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: none;\n"
"    border-radius: 50px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ccc\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #aaa\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"")
        self.restart_lesson.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/GUI\\../images/restart.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.restart_lesson.setIcon(icon2)
        self.restart_lesson.setIconSize(QtCore.QSize(60, 60))
        self.restart_lesson.setObjectName("restart_lesson")
        self.word_translation = QtWidgets.QLabel(parent=self.Center_widget)
        self.word_translation.setGeometry(QtCore.QRect(10, 110, 1271, 50))
        self.word_translation.setMinimumSize(QtCore.QSize(0, 50))
        self.word_translation.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.word_translation.setFont(font)
        self.word_translation.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.word_translation.setObjectName("word_translation")
        self.word_transcription = QtWidgets.QLabel(parent=self.Center_widget)
        self.word_transcription.setGeometry(QtCore.QRect(10, -10, 1271, 50))
        self.word_transcription.setMinimumSize(QtCore.QSize(0, 50))
        self.word_transcription.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.word_transcription.setFont(font)
        self.word_transcription.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.word_transcription.setObjectName("word_transcription")
        self.checkBox = QtWidgets.QCheckBox(parent=self.Center_widget)
        self.checkBox.setGeometry(QtCore.QRect(1060, 40, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.Layout_type = QtWidgets.QCheckBox(parent=self.Center_widget)
        self.Layout_type.setGeometry(QtCore.QRect(1060, 80, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Layout_type.setFont(font)
        self.Layout_type.setObjectName("Layout_type")
        self.Main_Study_Layout.addWidget(self.Center_widget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.Main_Study_Layout.addItem(spacerItem1)
        self.W_L_button_layout = QtWidgets.QHBoxLayout()
        self.W_L_button_layout.setContentsMargins(400, -1, 400, -1)
        self.W_L_button_layout.setSpacing(20)
        self.W_L_button_layout.setObjectName("W_L_button_layout")
        spacerItem2 = QtWidgets.QSpacerItem(5, 70, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.W_L_button_layout.addItem(spacerItem2)
        self.L_answer = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.L_answer.setMinimumSize(QtCore.QSize(0, 70))
        self.L_answer.setMaximumSize(QtCore.QSize(16777215, 70))
        self.L_answer.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: none;\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #c71050\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #e0487d\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #e86413\n"
"        );\n"
"    }")
        self.L_answer.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/GUI\\../images/cross.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.L_answer.setIcon(icon3)
        self.L_answer.setIconSize(QtCore.QSize(64, 64))
        self.L_answer.setObjectName("L_answer")
        self.W_L_button_layout.addWidget(self.L_answer)
        self.W_answer = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.W_answer.setMinimumSize(QtCore.QSize(0, 70))
        self.W_answer.setMaximumSize(QtCore.QSize(16777215, 70))
        self.W_answer.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: none;\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #10a350\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #3cd665\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #28d413\n"
"        );\n"
"    }")
        self.W_answer.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/GUI\\../images/checked.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.W_answer.setIcon(icon4)
        self.W_answer.setIconSize(QtCore.QSize(64, 64))
        self.W_answer.setObjectName("W_answer")
        self.W_L_button_layout.addWidget(self.W_answer)
        spacerItem3 = QtWidgets.QSpacerItem(5, 70, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.W_L_button_layout.addItem(spacerItem3)
        self.Main_Study_Layout.addLayout(self.W_L_button_layout)
        self.translation_layout = QtWidgets.QHBoxLayout()
        self.translation_layout.setContentsMargins(160, 10, 160, 0)
        self.translation_layout.setSpacing(90)
        self.translation_layout.setObjectName("translation_layout")
        spacerItem4 = QtWidgets.QSpacerItem(5, 70, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.translation_layout.addItem(spacerItem4)
        self.translation = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.translation.setEnabled(True)
        self.translation.setMinimumSize(QtCore.QSize(0, 70))
        self.translation.setMaximumSize(QtCore.QSize(496, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.translation.setFont(font)
        self.translation.setStyleSheet("QPushButton {\n"
"    color: #eee;\n"
"    border: none;\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #7612b8\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #954af7\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #5b29f2\n"
"        );\n"
"    }")
        self.translation.setObjectName("translation")
        self.translation_layout.addWidget(self.translation)
        spacerItem5 = QtWidgets.QSpacerItem(5, 70, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.translation_layout.addItem(spacerItem5)
        self.Main_Study_Layout.addLayout(self.translation_layout)
        self.Back_widget = QtWidgets.QWidget(parent=self.Lesson_screen)
        self.Back_widget.setGeometry(QtCore.QRect(0, 0, 1280, 120))
        self.Back_widget.setMinimumSize(QtCore.QSize(1280, 120))
        self.Back_widget.setMaximumSize(QtCore.QSize(1280, 16777215))
        self.Back_widget.setObjectName("Back_widget")
        self.prev_page = QtWidgets.QPushButton(parent=self.Back_widget)
        self.prev_page.setGeometry(QtCore.QRect(280, 40, 100, 70))
        self.prev_page.setMinimumSize(QtCore.QSize(100, 70))
        self.prev_page.setMaximumSize(QtCore.QSize(100, 70))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.prev_page.setFont(font)
        self.prev_page.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: none;\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 rgb(199, 20, 47)\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 rgb(224, 53, 78)\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 rgb(232, 0, 0)\n"
"        );\n"
"    }\n"
"")
        self.prev_page.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("assets/GUI\\../images/return.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.prev_page.setIcon(icon5)
        self.prev_page.setIconSize(QtCore.QSize(80, 60))
        self.prev_page.setObjectName("prev_page")
        self.points_display = QtWidgets.QLabel(parent=self.Back_widget)
        self.points_display.setGeometry(QtCore.QRect(650, 70, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.points_display.setFont(font)
        self.points_display.setStyleSheet("\n"
"    QLabel {\n"
"        padding: 10px;            /* Padding around the text */\n"
"        border-radius: 15px;      /* Rounded corners */\n"
"\n"
"    }\n"
"\n"
"")
        self.points_display.setText("")
        self.points_display.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.points_display.setObjectName("points_display")
        self.pages.addWidget(self.Lesson_screen)
        self.Mode_Choose_screen = QtWidgets.QWidget()
        self.Mode_Choose_screen.setObjectName("Mode_Choose_screen")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.Mode_Choose_screen)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 1291, 721))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.Main_Mode_Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.Main_Mode_Layout.setContentsMargins(0, 0, 0, 0)
        self.Main_Mode_Layout.setSpacing(9)
        self.Main_Mode_Layout.setObjectName("Main_Mode_Layout")
        self.Back_widget_2 = QtWidgets.QWidget(parent=self.verticalLayoutWidget_3)
        self.Back_widget_2.setMinimumSize(QtCore.QSize(700, 120))
        self.Back_widget_2.setMaximumSize(QtCore.QSize(16777215, 120))
        self.Back_widget_2.setObjectName("Back_widget_2")
        self.prev_page_2 = QtWidgets.QPushButton(parent=self.Back_widget_2)
        self.prev_page_2.setGeometry(QtCore.QRect(280, 40, 100, 70))
        self.prev_page_2.setMinimumSize(QtCore.QSize(100, 70))
        self.prev_page_2.setMaximumSize(QtCore.QSize(100, 70))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.prev_page_2.setFont(font)
        self.prev_page_2.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: none;\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 rgb(199, 20, 47)\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 rgb(224, 53, 78)\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 rgb(232, 0, 0)\n"
"        );\n"
"    }\n"
"")
        self.prev_page_2.setText("")
        self.prev_page_2.setIcon(icon5)
        self.prev_page_2.setIconSize(QtCore.QSize(80, 60))
        self.prev_page_2.setObjectName("prev_page_2")
        self.Main_Mode_Layout.addWidget(self.Back_widget_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.Main_Mode_Layout.addItem(spacerItem6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.mode3ex = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        self.mode3ex.setMinimumSize(QtCore.QSize(700, 70))
        self.mode3ex.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.mode3ex.setFont(font)
        self.mode3ex.setObjectName("mode3ex")
        self.gridLayout.addWidget(self.mode3ex, 6, 0, 1, 1)
        self.mode_choose = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.mode_choose.setEnabled(True)
        self.mode_choose.setMaximumSize(QtCore.QSize(700, 70))
        font = QtGui.QFont()
        font.setPointSize(44)
        font.setBold(True)
        self.mode_choose.setFont(font)
        self.mode_choose.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mode_choose.setObjectName("mode_choose")
        self.gridLayout.addWidget(self.mode_choose, 1, 0, 1, 1)
        self.mode2stud = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        self.mode2stud.setMinimumSize(QtCore.QSize(700, 70))
        self.mode2stud.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.mode2stud.setFont(font)
        self.mode2stud.setObjectName("mode2stud")
        self.gridLayout.addWidget(self.mode2stud, 5, 0, 1, 1)
        self.mode1intro = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        self.mode1intro.setMinimumSize(QtCore.QSize(700, 70))
        self.mode1intro.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.mode1intro.setFont(font)
        self.mode1intro.setAutoFillBackground(False)
        self.mode1intro.setObjectName("mode1intro")
        self.gridLayout.addWidget(self.mode1intro, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem7, 7, 0, 1, 1)
        self.Main_Mode_Layout.addLayout(self.gridLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.Main_Mode_Layout.addItem(spacerItem8)
        self.pages.addWidget(self.Mode_Choose_screen)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1271, 721))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.groupGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.groupGrid.setContentsMargins(0, 0, 0, 0)
        self.groupGrid.setObjectName("groupGrid")
        self.pages.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.page_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 1271, 721))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.groupGrid_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.groupGrid_2.setContentsMargins(0, 0, 0, 0)
        self.groupGrid_2.setObjectName("groupGrid_2")
        self.pages.addWidget(self.page_2)
        self.Base_Layout.addWidget(self.pages)
        spacerItem9 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.Base_Layout.addItem(spacerItem9)

        self.retranslateUi(UNOlingo)
        self.pages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(UNOlingo)

    def retranslateUi(self, UNOlingo):
        _translate = QtCore.QCoreApplication.translate
        UNOlingo.setWindowTitle(_translate("UNOlingo", "UNOlingo"))
        self.MistakesLabel.setText(_translate("UNOlingo", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:700; color:#00007f;\">Mistakes:</span></p></body></html>"))
        self.Grade3.setText(_translate("UNOlingo", "<html><head/><body><p><br/></p></body></html>"))
        self.Grade4.setText(_translate("UNOlingo", "<html><head/><body><p><br/></p></body></html>"))
        self.GradesLabel.setText(_translate("UNOlingo", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:700; color:#00007f;\">Recent grades:</span></p></body></html>"))
        self.ResultsLabel.setText(_translate("UNOlingo", "<html><head/><body><p><span style=\" font-size:48pt; font-weight:700; color:#810031;\">Results</span></p></body></html>"))
        self.Grade1.setText(_translate("UNOlingo", "<html><head/><body><p><br/></p></body></html>"))
        self.Grade5.setText(_translate("UNOlingo", "<html><head/><body><p><br/></p></body></html>"))
        self.SaveAndExit.setText(_translate("UNOlingo", "Save and switch Lesson"))
        self.Repeat.setText(_translate("UNOlingo", "Next lesson"))
        self.AnswersLabel.setText(_translate("UNOlingo", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:700; color:#00007f;\">Correct answers: </span></p></body></html>"))
        self.Grade2.setText(_translate("UNOlingo", "<html><head/><body><p><br/></p></body></html>"))
        self.The_word.setText(_translate("UNOlingo", "WordLabel"))
        self.word_translation.setText(_translate("UNOlingo", "Translation"))
        self.word_transcription.setText(_translate("UNOlingo", "Transcription"))
        self.checkBox.setText(_translate("UNOlingo", "Show mistakes"))
        self.Layout_type.setText(_translate("UNOlingo", "Buttons layout "))
        self.translation.setText(_translate("UNOlingo", "Reveal Translation"))
        self.mode3ex.setText(_translate("UNOlingo", "Екзамен"))
        self.mode_choose.setText(_translate("UNOlingo", "Выбор режима"))
        self.mode2stud.setText(_translate("UNOlingo", "Изучение слов"))
        self.mode1intro.setText(_translate("UNOlingo", "Слова в этом уроке"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UNOlingo = QtWidgets.QWidget()
    ui = Ui_UNOlingo()
    ui.setupUi(UNOlingo)
    UNOlingo.show()
    sys.exit(app.exec())
