# Form implementation generated from reading ui file 'assets/gui/loading.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Splash(object):
    def setupUi(self, Splash):
        Splash.setObjectName("Splash")
        Splash.resize(640, 360)
        self.labelLoading = QtWidgets.QLabel(parent=Splash)
        self.labelLoading.setGeometry(QtCore.QRect(220, 50, 191, 151))
        self.labelLoading.setObjectName("labelLoading")
        self.progressBar = QtWidgets.QProgressBar(parent=Splash)
        self.progressBar.setGeometry(QtCore.QRect(40, 242, 571, 41))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background: #f3f3f3\n"
"    padding: 10 px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #5b29f2\n"
"        );   \n"
"\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.getUpdate = QtWidgets.QPushButton(parent=Splash)
        self.getUpdate.setGeometry(QtCore.QRect(120, 180, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.getUpdate.setFont(font)
        self.getUpdate.setStyleSheet("QPushButton {\n"
"    color: #eee;\n"
"    border: none;\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #7612b8\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #954af7\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #5b29f2\n"
"        );\n"
"    }")
        self.getUpdate.setObjectName("getUpdate")
        self.rejectUpdate = QtWidgets.QPushButton(parent=Splash)
        self.rejectUpdate.setGeometry(QtCore.QRect(120, 270, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.rejectUpdate.setFont(font)
        self.rejectUpdate.setStyleSheet("QPushButton {\n"
"    color: #eee;\n"
"    border: none;\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 rgb(170, 170, 255)\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 rgb(211, 203, 255)\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 rgb(149, 149, 223)\n"
"        );\n"
"    }")
        self.rejectUpdate.setObjectName("rejectUpdate")

        self.retranslateUi(Splash)
        QtCore.QMetaObject.connectSlotsByName(Splash)

    def retranslateUi(self, Splash):
        _translate = QtCore.QCoreApplication.translate
        Splash.setWindowTitle(_translate("Splash", "Form"))
        self.labelLoading.setText(_translate("Splash", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:700; color:#00007f;\">Loading</span></p></body></html>"))
        self.getUpdate.setText(_translate("Splash", "Update app"))
        self.rejectUpdate.setText(_translate("Splash", "Maybe later"))
